### ISSUE TITLE
add delete feature for supermarket-ctl

### ISSUE THREAD

**Issue by stephenlauck** [chef/supermarket#1090]
As a customer I would like to delete/unshare certain versions of a cookbook without deleting/unsharing the whole cookbook.

I would like to run a command like 'supermarket-ctl delete cookbook NAME -v VERSION'

**Comment by nellshamrell** [comment]
I support this being available to users of private Supermarket, but would rather it not be available in public Supermarket.  The reason is that whenever someone uploads a cookbook version to public Supermarket it is almost immediately copied by Berks, which means if someone were to accidentally upload a cookbook version with credentials in it, then unshare that version, those credentials would have been already copied by Berks.  When this happens in public Supermarket I generally advise the user to invalidate those credentials to be sure that no one can use them.

That said, I think this would be fine as an addition to private Supermarket.

**Comment by nellshamrell** [comment]
There is ongoing discussion of this in #954.  Going to defer discussion to there, we will continue it in 2016 and make a decision whether to have the ability to remove cookbooks from public/private supermarkets.
