### ISSUE TITLE
supermarket-omnibus package does not include SendMail

### ISSUE THREAD

**Issue by nellshamrell** [chef/supermarket#1093]
SendMail is not being installed with Supermarket omnibus package, which means “Adopt Me” emails go nowhere
I found this out by examining the logs and spotting
=> /var/log/supermarket/sidekiq/current <==
2015-07-29_21:48:10.41237 sh: 1: /usr/sbin/sendmail: not found
2015-07-29_21:48:10.41285 2015-07-29T21:48:10.412Z 16760 TID-aepr4 Sidekiq::Extensions::DelayedMailer JID-a52edf298b1ab1fa2c14e232 INFO: done: 0.093 sec

This is easily remedied by install send-mail with apt or yum, but it should be a part of the omnibus package.

**Comment by smith** [comment]
The more common and easier to use MTA on Linux would be Postfix rather than Sendmail.

Note that the Chef server does not handle this for you and asks that you have mail relay configured as a prerequisite: https://docs.chef.io/install_server_pre.html#mail-relay

Analytics also requires you to set this up yourself: https://docs.chef.io/install_analytics.html#prerequisites

I would recommend that this issue be closed so that, regardless of the merits of whether or not this should be set up by our installer, it works the same way as other Chef server products.

**Comment by nellshamrell** [comment]
Understood, and that's a good point.  Leaving this open until I update the Supermarket docs.
