### ISSUE TITLE
Create Supermarket Status page

### ISSUE THREAD

**Issue by kowal** [chef/supermarket#1100]
Today we started observing following errors during ```berks vendor```:
```
/opt/chefdk/embedded/lib/ruby/2.1.0/net/http.rb:879:in `initialize': \
Connection timed out - connect(2) for "app-supermarket-prod-i-c663c400.opscode.us" port 443 (Errno::ETIMEDOUT)
```

It made me think that it would be really nice to have simple "Status" page on https://supermarket.chef.io/ when one can quickly check if service is operable.

If this could be also available as API, Berkshelf could use it and print meaningful error messages in some cases.

**Comment by kowal** [comment]
I've found https://supermarket.chef.io/status however it does not indicate any errors and we still can't get response..

**Comment by kowal** [comment]
For anyone interested: there is http://status.chef.io/ - I would just suggest putting link to that page somewhere in Supermarket's footer.

**Comment by nellshamrell** [comment]
Good idea, ty!

**Comment by dmerrick** [comment]
This is a great idea. Agreed that it should be added to status.chef.io, and it should include elevated error rates in addition to straight downtime.

**Comment by nellshamrell** [comment]
Thank you again.  The link to status.chef.io has been added in the Supermarket footer.  We are also looking at a more robust monitoring solution for public Supermarket on our end to notify us of potential issues with Berkshelf, etc, so that status.chef.io will be updated quicker.  We are not going to update the status API endpoint itself at this time, because that would rely on Supermarket to test things that should be tested externally.  We will be adding in external testing to observe /universe to ensure that Berkshelf is still functional.

**Comment by kowal** [comment]
Great! Thanks.
