### ISSUE TITLE
Disabling ssl and nginx force_ssl doesn't change cookbook download url and berks api endpoint

### ISSUE THREAD

**Issue by ChastinaLi** [chef/supermarket#1108]
Using supermarket 2.0.0, we disabled ssl and nginx force_ssl:
```ruby
supermarket['nginx']['force_ssl'] = false
supermarket['ssl']['enabled'] = false
```
However, we don't see a change in the universe.json download_url and location path. They still point to `https` and `443`.
```
"location_path":"https://supermarket:443/api/v1",
"download_url":"https://supermarket:443/api/v1/cookbooks/nginx/versions/1.5.91/download",
```
How do we configure download_url and location_path to point to `http` and `80` now that we've disabled ssl? 

(We looked at this issue: [Sharing a cookbook binds the download_url and location_path to the host attribute and doesn't update correctly](https://github.com/chef/supermarket/issues/816). But flushing Universe Cache doesn't seem to solve the problem, we are still getting the `https` and `443` urls back)

**Comment by TinaTina** [comment]
Okay, we got it to work.
The issue was this PR [Correct the nginx X-Forwarded-Proto lines so that rails request.protocol is right](https://github.com/chef/omnibus-supermarket/pull/10).
The PR hardcoded:
```ruby
location / {
   ......
   proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
}
```
to 
```ruby
location / {
   ......
   proxy_set_header X-Forwarded-Proto https;
}
```
which sets the download_url protocol to `https` even though we diabled `ssl` and `nginx force ssl` and changed the port to `80` and protocol to `http`.

I wonder if nginx rails conf can be templated to map  `proxy_set_header X-Forwarded-Proto` [here](https://github.com/chef/omnibus-supermarket/blob/master/cookbooks/omnibus-supermarket/templates/default/rails.nginx.conf.erb#L123) to the `default['supermarket']['protocol']` node attribute [here](https://github.com/chef/omnibus-supermarket/blob/master/cookbooks/omnibus-supermarket/attributes/default.rb#L332).

Thanks

**Comment by nellshamrell** [comment]
Glad to hear you got it working and excellent suggestion!

**Comment by TinaTina** [comment]
@nellshamrell thank you for responding to our questions so quickly every time. We really appreciate it :smiley:

**Comment by nellshamrell** [comment]
You are quite welcome!

**Comment by amaltson** [comment]
Going to :+1: on helping us out so much @nellshamrell. We were flushing the UniverseCache but the nginx change was the culprit all along :smile:

**Comment by nellshamrell** [comment]
I feel the ops love!  :heart:
