### ISSUE TITLE
Transferring cookbook ownership should make the current owner a contributor

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1224]
Transferring ownership of a cookbook to a new owner current removes the existing owner entirely.  It should instead make the existing owner a contributor.

**Comment by mvdkleijn** [comment]
Why? :smile: Your suggestion assumes that the cookbook still contains code of the original owner after transfer. Also keep in mind that it iss ownership of the supermarket entry / name, not the cookbook itself...

Transferring ownership might also occur due to someone claiming the name in the supermarket in the past, never doing anything with it (empty cookbook for example) and then transferring ownership of the name to another user that has a full from-scratch cookbook that he uses the name for.

And yes, this does happen... even the Chef guys themselves claim names and then neglect to really use them.

So personally for me: :-1:

**Comment by robbkidd** [comment]
Another option is to add a checkbox to the Transfer Ownership form:
`[ ] Make current owner (probably you) a contributor`

And then we debate whether it's checked or not checked by default.

**Comment by nellshamrell** [comment]
I support @robbkidd's idea of making a checkbox (or something to that effect) in the Transfer Ownership form.

**Comment by tas50** [comment]
Some sort of checkbox would be totally acceptable UX flow
