### ISSUE TITLE
Allow hiding the "new supermarket announcements"

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#1248]
There's no way to get rid of the new supermarket announcements and they're not new at this point.  We should allow Xing them out until new ones appear much like Github pops up new features in the top right corner.

**Comment by nellshamrell** [comment]
Good first step would be to allow someone to click an "x" or something on the New Supermarket Announcements banner.

Good next step would be to check how long it's been since we last added an announcement (not sure how that is tracked off hand) and, if it's been more than a couple of weeks, don't show the banner.

A good final step would be, if someone is signed in and the newest announcement is older than the last time they signed in, don't show the banner.  (If they were to view Supermarket without being logged in, they would still see the banner).

**Comment by tas50** [comment]
Those steps look good
