### ISSUE TITLE
/sign-out doesn't redirect you to the correct `chef_server_url`/id URL

### ISSUE THREAD

**Issue by mengesb** [chef/supermarket#1295]
When using on-prem supermarket and chef-server, clicking 'sign-out' which is relative URL `/sign-out` to supermarket creates a message:

``` text
You have been signed out of Supermarket but may still be signed in to your Chef account. Visit /id to sign out completely.
```

However `/id` is a relative link, not a re-direct to the `chef_server_url` parameter specified in supermarket. This is similar in issue to #927 however it isn't that it is redirecting to Chef's hosted identity, but rather that the link is more like `nil`+`/id` for the URL.

I'm currently using the last released versions of all cookbooks.

**Comment by mengesb** [comment]
Using the [chef-cookbooks/supermarket-omnibus-cookbook](https://github.com/chef-cookbooks/supermarket-omnibus-cookbook) cookbook I attempted to set `chef_identity_url` however that didn't result in the update to the `ENV[CHEF_IDENTITY_URL]` export in the environment file.

Any idea as to a fix, and if this is truly a problem with [chef/supermarket](https://github.com/chef/supermarket) or [chef-cookbooks/supermarket-omnibus-cookbook](https://github.com/chef-cookbooks/supermarket-omnibus-cookbook)

Should I, instead, be using this cookbook directly as opposed to the omnibus one?

**Comment by robbkidd** [comment]
For the community Supermarket site, we use a wrapper cookbook to customize the `supermarket_omnibus` node attributes and then run the default recipe in chef-cookbooks/supermarket-omnibus-cookbook. So I still recommend today using `supermarket-omnibus-cookbook`.

Here's how we handle the Chef server/identity URLs (quick version):
* `chef_identity_url` is declared somewhere (a data bag in our case)
* node['supermarket_omnibus']['chef_server_url'] is set equal to the declared `chef_identity_url`
* `chef_identity_url` is included as a key in a hash that is saved to `node['supermarket_server']['config']`
* both of these node attributes are then used by [the `supermarket_server` resource](https://github.com/chef-cookbooks/supermarket-omnibus-cookbook/blob/master/recipes/default.rb#L11-L17) in supermarket-omnibus-cookbook's default recipe

I have stared into the layers of abstraction involved and they have stared back into me. I plan to do some more staring in the near future. A few Chefs I have talked to about this are also thinking through what it would take to remove some of these layers of abstraction, but that's going to take a bit of time.

Some lower-level details tracing up from `chef_ingredient` resource that does most of the work.

* Internal to the `supermarket_server` resource in chef-cookbooks/supermarket-omnibus-cookbook is a [`chef_ingredient` resource](https://github.com/chef-cookbooks/supermarket-omnibus-cookbook/blob/master/libraries/supermarket_server.rb#L84-L99) that know how to install and configure an omnibus package.
* A hash is passed to the [`chef_ingredient`'s `config` property](https://github.com/chef-cookbooks/supermarket-omnibus-cookbook/blob/master/libraries/supermarket_server.rb#L86). This hash contains the key/values that will get written out to `/opt/supermarket/supermarket.json`.
    * `merged_supermarket_config` is [an internal method to merge the hash given with properties set directly](https://github.com/chef-cookbooks/supermarket-omnibus-cookbook/blob/master/libraries/supermarket_server.rb#L49-L60) on the `supermarket_server` resource
* In our customizing wrapper cookbook, we retrieve a data bag that contains an `env` "hash." `env['chef_identity_url']` is our Chef Server's URL for oauth.
* We set `node.set['supermarket_omnibus']['chef_server_url'] = app['env']['chef_identity_url']` in our wrapper's default recipe so that the [`supermarket_server` resource](https://github.com/chef-cookbooks/supermarket-omnibus-cookbook/blob/master/recipes/default.rb#L12) gets its Chef Server set.

**Comment by mengesb** [comment]
So what I'm using to deploy is terraform using the following plan: [tf_chef_supermarket](https://github.com/mengesb/tf_chef_supermarket). In the chef provisioner I pass a JSON segment with all the attributes to set for supermarket_omnibus. Here's a generated segment:

```json
{
  "chef_client": {
    "init_style": "none"
  },
  "fqdn": "costco.[DOMAINTLD]",
  "supermarket_omnibus": {
    "chef_oauth2_app_id": "[APP_ID]",
    "chef_oauth2_secret": "[APP_SECRET]",
    "chef_oauth2_verify_ssl": true,
    "chef_server_url": "https://ramsey.[DOMAINTLD]",
    "config": {
      "ssl": {
        "certificate": "/var/opt/supermarket/ssl/costco.[DOMAINTLD].crt",
        "certificate_key": "/var/opt/supermarket/ssl/costco.[DOMAINTLD].key"
      }
    }
  },
    ...
  },
  "tags": []
}
```

I've sanitized a few things, but for the most part that's the complete node attribute provided at time of provisioning to chef.

As my prior comment suggests, I've attempted adding a full stanza to influence directly the supermarket cookbook (called within the omnibus one):
```
  ...
  },
  "supermarket": {
    "chef_identity_url": "https://ramsey.[DOMAINTLD]"
  },
  ...
```
And also attempted to specify it under supermarket_omnibus:
```
  ...
  },
  "supermarket_omnibus": {
    "chef_identity_url": "https://ramsey.[DOMAINTLD]",
    ...
  },
  ...
```

However both attempts at running `chef-client` to see if the `/var/opt/supermarket/etc/env` file updates result in no changes. I do know the file is managed, because manual changes to correct `CHEF_IDENTITY_URL` and then subsequent `chef-client` runs result in it being changed back from the correct value to `/id`. One very quick fix that I can see is in the list of exports, instead of providing different variables for `CHEF_IDENTITY_URL` and `CHEF_SERVER_URL` is to just overload the `CHEF_IDENTITY_URL`. I am setting the `CHEF_SERVER_URL` (as required), however in that export file you could make the following change:
```
-  export CHEF_IDENTITY_URL="#{node['supermarket']['chef_identity_url']}/id"
+  export CHEF_IDENTITY_URL="${CHEF_SERVER_URL}/id"
```
This results in the `/var/opt/supermarket/etc/env` file using its own local variable, which is in effect `node['supermarket']['chef_server_url']`. I'm not quite sure why you might want the chef server different from the identity server, they reside on the same server... however i guess there might be that edge case where the oc-id service doesn't reside on the chef-server?

**Comment by RajeshPaul38** [comment]
Have verified that the URL is pointing to the chef server URL itself. Sharing screenshot below.
 ![Screenshot 2021-08-16 at 9.55.33 PM.png](https://images.zenhubusercontent.com/60b7868792ea6cd3231262be/b62f47a3-d966-41df-bba5-4b4f20b408da)
