### ISSUE TITLE
How to integrate TDD with Supermarket?

### ISSUE THREAD

**Issue by abhi-paul** [chef/supermarket#1390]
My Question is, to share any tagged version of cookbook into the supermarket how to make sure the **cookbook** is **passed**  through the TestDrivenDevelopment (**TDD**) process.

I know TDD tools like Rake,Serverspec,Chefspec,Foodcritics are available, but the question is **how to make sure before anyone publishes a cookbook into the supermarket it's pass through Rake?**

Is there any tools/utility's are available? Is there any glue between Rake and knife-supermarket plugin?
@nellshamrell @robbkidd

**Comment by robbkidd** [comment]
> I know TDD tools like Rake,Serverspec,Chefspec,Foodcritics are available, but the question is how to make sure before anyone publishes a cookbook into the supermarket it's pass through Rake?

Because Supermarket was designed to be a fairly open cookbook sharing platform, Supermarket itself does not prevent a cookbook from being published based on quality. There is a simple "quality metrics" feature that displays—under the Quality tab for a cookbook—aspects about a cookbook version once published. Today, it will show the results of a foodcritic run and there are plans for it to show more in the future.

For private cookbooks in a private Supermarket, ensuring published cookbooks meet some baseline standards is usually a responsibility given to a continuous integration (CI) pipeline. Many choose to make the CI pipeline perform the action of publishing a cookbook after the cookbook passed the tests of the pipeline. It is in the pipeline that you would dictate Foodcritic (linting), ChefSpec (unit), and ServerSpec (integration) tests must pass after which the pipeline would perform the publish. This pattern is so common that there exists [delivery-truck](https://github.com/chef-cookbooks/delivery-truck), a build cookbook that automates the testing and publication of a cookbook to Supermarket and/or a Chef Server. (Build cookbooks are used in the Workflow component of [Chef Automate](https://www.chef.io/automate/).)

Many public cookbooks use badges in their READMEs to communicate status of testing. If your internal CI pipeline has the ability to display badges, that may be something to consider also.

**Comment by abhi-paul** [comment]
Does it possible that without installing **"Chef Automate Server"** only by using "**delivery-truck**"  build cookbook automates the testing and publication of a cookbook to Supermarket and/or a Chef Server?
@robbkidd

**Comment by robbkidd** [comment]
Yes. It is possible to use delivery-truck without Chef Automate. It may be a lot of labor.

**Comment by abhi-paul** [comment]
Hi @robbkidd 
I did little digs around about "Continuous Integration & Continuous Delivery" and found there other tools called "GitLab CI/CD" or "TeamCity" how "Chef Delivery/Workflow " is different from others?

Since ChefAutomate (workflow+visibility+complaince) is coming with premium version does is possible only to use "Chef Delivery/Workflow" without the premium tag if yes then how?

**Comment by robbkidd** [comment]
I don't have any documentation for using delivery-truck outside of Automate Workflow. It is theoretically possible, but would involve you re-implementing a CI pipeline that acts like Automate.

At this point, I think I need to direct your questions to venues more appropriate for Q&A. We use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

There is a [Chef mailing list](https://discourse.chef.io/) you can join and ask questions. On StackOverflow, you can tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef). There is also a [Chef Community Slack](http://community-slack.chef.io/) chat where discussions can be had a bit more synchronously.
