### ISSUE TITLE
How to map Private Supermarket Search keyword and cookbook name?

### ISSUE THREAD

**Issue by abhi-paul** [chef/supermarket#1393]
I have one general question let's say, I publish a cookbook with name "webapache" but while searching into the supermarket given keyword is "HTTPD Installer", now **how to map "HTTPD Installer"->"webapache"** or vice versa?
**Can we add tag kind of thing** while publishing any cookbook into the supermarket, so that we can add possible search keyword against of any cookbook?
@robbkidd @nellshamrell

**Comment by nellshamrell** [comment]
Hi @abhi-paul - that functionality does not currently exists, though it is something we can potentially add to our backlog to investigate (it will need to be prioritized along with our current and future work)

**Comment by robbkidd** [comment]
A quick follow-up @abhi-paul:

Without a code change, it _is_ possible for a cookbook author to associate a cookbook with keywords in search. Currently, a cookbook's name, description, and author are the fields from the metadata of a cookbook that get indexed for the search. If you were to include "HTTPD" in the description of your "webapache" cookbook, "webapache" cookbook would be included in the search results.

For example, [a search for "command_alias"](https://supermarket.chef.io/cookbooks?q=command_alias) returns the "magic_shell" cookbook because "command" and "alias" appear in the description.
