### ISSUE TITLE
What would SAML-based authentication look like?

### ISSUE THREAD

**Issue by nathenharvey** [chef/supermarket#1437]
Chef server allows for SAML-based authentication.  The Supermarket should support this as well.

This issue should be used for tracking and understanding what that work looks like so that we can plan for it accordingly.  It's likely that this work will involve updates to [oc-id](https://github.com/chef/oc-id) as that is used during the Supermarket authentication process.

**Comment by nathenharvey** [comment]
The initial request for this came through [the feedback site](https://feedback.chef.io/forums/301644-chef-product-feedback/suggestions/16284229-supermarket-oauth2-authentification-against-a-chef).

**Comment by nellshamrell** [comment]
To investigate - does Supermarket work with a Chef Server that is part of an automate cluster?

**Comment by jakauppila** [comment]
Where is this on the roadmap? We use Chef local mode on our servers and currently store our cookbooks in Git so we vendor them directly out of there when pushing changes into our pipeline. To make for easier release management we're looking to publish the cookbooks once versioned. Our options right now is kind of limited to Artifactory because of the requirement to run Chef server for Supermarket.

**Comment by tas50** [comment]
Closing this out since we're tracking this in Aha. It's in the works.
