### ISSUE TITLE
API to support tools search by type

### ISSUE THREAD

**Issue by alexpop** [chef/supermarket#1454]
Tools uploaded to the supermarket have a `Type` field (Handler, Compliance Profile, etc).

This feature request is for adding a `type` parameter to the search API.

It will allow tools like inspec to only list compliance profiles via:

```
inspec supermarket profiles
```

**Comment by robbkidd** [comment]
Background: search scoped by `type` is currently supported in [the UI tools search](https://github.com/chef/supermarket/blob/913bb07bde7f90f36f450fba2713065b7951c775/src/supermarket/app/controllers/tools_controller.rb#L19-L25), but not in [the API tools search](https://github.com/chef/supermarket/blob/913bb07bde7f90f36f450fba2713065b7951c775/src/supermarket/app/controllers/api/v1/tools_controller.rb#L51-L53) endpoint because it currently lacks any interpretation of a `type` parameter there.
