### ISSUE TITLE
Private Supermarket user with public_key == nil

### ISSUE THREAD

**Issue by lehn-etracker** [chef/supermarket#1482]
Some days ago I've build a private version of supermarket, release 2.8.39 connected to private chef12 server using chef_oauth2 interface.

The authentication and authorization is working for the web ui, but not for `knife cookbook site share`. The reason seems to be an empty `public_key`-field within the `User` object.

_I've tried to update the `public_key`-field via `supermarket-ctl console`, but was not able to test further. I will report the results during the next days._

**Comment by robbkidd** [comment]
Supermarket populates the `User`'s public key with the primary public key information given by the Chef Server after a user has logged in to the web UI. The key is part of the information the Chef Server's oauth2 service provides. The two most common cases of `knife [cookbook site|supermarket]` command erroring with a message about the user's key are when

* the user has never logged in to Supermarket web (so public_key is empty because the oauth2 tango has never been danced)
* the user has created a new key pair in the Chef Server and had not logged-out and then logged back in to Supermarket web (the auth2 tango must be danced again for Supermarket to know about the new key in Chef Server)

That is the current, admittedly-frustrating state of things. There are a couple of authentication-related feature requests in our backlog that are influencing what might go on our roadmap in the new year. Making this key exchange business more pleasant is among them.

**Comment by lehn-etracker** [comment]
@robbkidd Thanks for all your details.

1. updating the users `public_key` is a valid workaround for my problem
2. i don't know, if my colleges have had signed out and resigned in into the supermarket before retrying to share any cookbooks again, but I know, that they have changed there chef password right before using it via `knife user edit`. 

The curious thing is, there knife access to the chef server did stop working also. I had to publish there public key again into the chef server via my knife access. I guess, changing the password this way was my pitfall.

**Comment by robbkidd** [comment]
I don't expect a password change to affect `knife [cookbook site|supermarket]` command success, but a changing of keys definitely requires a user to log in fresh to the Supermarket web interface to update Supermarket's copy of the user's public key.

**Comment by nellshamrell** [comment]
Going to go ahead and close this, but if you have further issues with this please feel free to re-open.
