### ISSUE TITLE
Missing CSS in Chef Supermarket 2.8.43

### ISSUE THREAD

**Issue by chrisgit** [chef/supermarket#1496]
We have upgraded our Chef Supermarket to 2.8.43 and unfortunately the pages do not render correctly.

If you put a browser into development mode you can see that a 404 is being returned on a (dynamically named?) CSS file, typically called application-<id>.css in the assests folder.

Is anyone else having the same thing?

**Comment by robbkidd** [comment]
@chrisgit This could be caused by an upgrade when the "rails" service has not been restarted after the upgrade. The running web service is still referencing an `application-<hash>.css` for the previous version which was removed by the upgrade process and replaced by a different `application-<hash>.css`. You should be able to `sudo supermarket-ctl restart` (which will restart all the Supermarket services) to resolve this problem if that is the cause.

**Comment by chrisgit** [comment]
@robbkidd Thank you for your response

````
sudo supermarket-ctl restart
````

Did indeed work. Once again, thanks.

**Comment by robbkidd** [comment]
Excellent! I'm glad you're working again, @chrisgit.
