### ISSUE TITLE
why is supermarket depsolver faster than chef-server?

### ISSUE THREAD

**Issue by kplimack** [chef/supermarket#1560]
Its briefly mentioned in docs "When Berkshelf is connected to a Private Supermarket’s API, Berkshelf runs speed up", but not documented anywhere as to why.  I've confirmed that it is indeed light years faster.  What are the key differrences between solving against a `:chef_server` vs a _supermarket_?

**Comment by ryanjfrizzell** [comment]
+1 losing our minds understanding why we all the sudden *need*  a private supermarket to function

**Comment by nellshamrell** [comment]
@kplimack Let me do some research on this and get back to you on the key differences between solving against a :chef_server vs. a supermarket.

@ryanjfrizzell are you referring to needing a private supermarket for depsolving?  Or in general?

**Comment by lamont-granquist** [comment]
The depsolver is client-side.  What you're pulling down is the /universe endpoint which is just a json blob of every cookbook version stored in the server or in the [private] supermarket.  Whatever the difference is, it should be expressed in that universe endpoint.  I'd first suspect that the chef server had lots of old cookbook versions and possibly circular deps or other pathologies that were slowing down the depsolver and that cleaning up old cookbook versions would fix the speed problem.

Also installing the `dep_selector` gem so that berkshelf uses gecode might speed things up (although sometimes the ruby error formatter in dep_selector breaks things worse than using molinillo).

Upgrading molinillo may also help.

**Comment by lamont-granquist** [comment]
Its possible that there might be some kind of code bug here as well.  But you haven't provided any kind of replication case, so its not possible to say.  A private supermarket will be faster than the public supermarket because the /universe can be trimmed down.  If you only mirror the cookbooks that you use and only pull down the latest versions and not every version, the the depsolver has to do much less work than doing solutions against every cookbook and every version of those cookbooks that have ever been uploaded to the public site.

**Comment by tas50** [comment]
Closing this out since the answer is in the comment above.
