### ISSUE TITLE
Update Redis to 6.2.6 for CVE fixes

### ISSUE THREAD

**Issue by tas50** [chef/supermarket#2284]
**Context: ** Redis version currently used has CVEs identified on it. This needs to be upgraded to 6.2.6 to remove vulnerabilities
**Acceptance criteria: **
- [ ] Version to use https://github.com/redis/redis/releases/tag/6.2.6
- [ ] Add scenarios to test if needed

**Comment by dheerajd-msys** [comment]
Reference for finding out the hashes : https://github.com/redis/redis-hashes. We can update it somewhere in our doc to let everyone know.

**Comment by RajeshPaul38** [comment]
Yes @dheerajd-msys that would be useful. But in case we don't find the checksum anywhere there is always a way to get the checksum in our local system i.e. by downloading the `package-version.tar.gz` and then running the following command:
`sha256sum <package.tar.gz>` -> This is returning `5b2b8b7a50111ef395bf1c1d5be11e6e167ac018125055daa8b5c2317ae131ab`
The result matches with the one that is mentioned in the link that you have provided: https://github.com/redis/redis-hashes

So we can use this approach instead of looking it up in the internet.

**Comment by RajeshPaul38** [comment]
Here's the PR to omnibus-supermarket for adding redis 6.2.6 in omnibus
https://github.com/chef/omnibus-software/pull/1475

This needs to be merged before we can use redis 6.2.6 in supermarket.

**Comment by RajeshPaul38** [comment]
omnibus-supermarket changes are merged. Need to use 6.2.6 redis in supermarket.

**Comment by RajeshPaul38** [comment]
Here's the supermarket build link with latest omnibus-software redis default version  i.e. 6.2.6. No changes required in supermarket code.
https://buildkite.com/chef/chef-supermarket-main-omnibus-adhoc/builds/241#e6cc745e-b95d-4ca0-b870-883756bc6604

**Comment by RajeshPaul38** [comment]
Closing this ticket as the necessary changes are done in omnibus-software. No changes needed in supermarket repo as it takes the default redis version from omnibus and it has been done there.
