### ISSUE TITLE
"Sign out" does not deauthorize cookie session

### ISSUE THREAD

**Issue by rhass-r7** [chef/supermarket#495]
It seems the session ID stored in the cookie does not get deauthorized once a user presses the "Sign out" button. One interesting thing about this is the value for _supermarket_session changes after each "login."
## Steps to Reproduce:
- [ ] Login
- [ ] Click "sign out" from the user drop-down.
- [ ] Login again

You should not be prompted for any credentials.

**Comment by 8la** [comment]
This still the same? How can i logout with a self hosted supermarket? Link takes me to my-supermarket-url/id but calims "This page does not exists"

**Comment by robbkidd** [comment]
Because Supermarket login is dependent on oc-id, the oauth provider within a Chef Server, to fully log out of Supermarket (public or self-hosted), you must log out of the associated Chef Server as well. 

What version of Supermarket are you self-hosting? What link is taking you to `<your-supermarket-url>/id`? In the current version, when a logged in user selects "Sign out" from the drop-down menu under their profile picture, the link is `<your-supermarket-url>/sign-out`.

**Comment by 8la** [comment]
After clicking on that link to signout, there is a mesage on the page that says: _You have been signed out of Supermarket but may still be signed in to your Chef account. Visit **/id** to sign out completely._

The problem was that using supermarket-omnibus-cookbook the attribute `default['supermarket_omnibus']['config']['chef_identity_url']` was not being set. Once i set the attribute on my wrapper cookbook attributes file, the link points to the right url: `https://your.chef-server.url/id`

**Comment by robbkidd** [comment]
Ah, yes, the "you're still logged in to your Chef account" message. I'm glad you got that figured out!
