### ISSUE TITLE
Missing public key

### ISSUE THREAD

**Issue by raskchanky** [chef/supermarket#873]
Earlier today, a user discovered that his public key was missing from his `User` record, which was preventing him from sharing cookbooks.  Implement a way to keep user details in sync with Hosted Chef, so this kind of thing doesn't happen again.

**Comment by Hakkal** [comment]
Hi , I am new to use this technology . can you please guide me how can i use ssh key in inspec for a user ....

**Comment by robbkidd** [comment]
Hi, @Hakkal and welcome!

You have found yourself on an old and closed issue about Chef Supermarket and key pairs. Generally, you want to open new discussions for a new question instead of adding a comment to an old question.

It sounds like you have questions about InSpec, which is a different project than Supermarket. Have you read [the InSpec documentation](https://www.inspec.io/docs/) or gone through the tutorials there? I recommend them. If you're still having trouble, the [community](https://www.inspec.io/community/) is a great place to reach out for help from others, in the [mailing list/web forums](https://discourse.chef.io/c/inspec) or in [the Chef Community chat (Slack)](http://community-slack.chef.io/).
