### ISSUE TITLE
Cookbooks with only metadata.json are triggering FC031

### ISSUE THREAD

**Issue by troyready** [chef/supermarket#884]
I just used stove to upload a new version of [a cookbook](https://supermarket.getchef.com/cookbooks/chef-splunk-windows#foodcritic), and the lack of a metadata.rb file seems to be triggering foodcritic rule FC031 (even though a metadata.json file is present)

![image](https://cloud.githubusercontent.com/assets/1806418/4778200/f3797df2-5be0-11e4-8d39-80e53d6e7d62.png)

**Comment by lamont-granquist** [comment]
@sethvargo i'm fairly confident that you're incorrect, and that metadata.rb should be shipped to supermarket -- similar to the gemspec still being uploaded to rubygems.  we will still continue to run foodcritic against the artifacts that are uploaded to it.  running it against the github url is a pretty complete non-starter, that won't work and we wont implement that.

We have one bikeshed in supermarket on this issue already #930 which really covers the bikeshed issues better.  See noah's comment there about gemspec and the setup.py for PyPI, which I think covers by analogy why we should mandate both metadata.rb and metadata.json

That said we've got acmrp/foodcritic#352 which addresses the tactical problem of having foodcritic read metadata.json instead of metadata.rb if it exists.

I also want to look at fixing https://github.com/chef/fieri so when supermarket runs foodcritic that it respects the .foodcritic file or at least invoke it so that it shuts off the errant FC warnings for now.

Anyway, there's a better issue in this repo for the bikeshed, and the other repos are where the tactical problems should be solved, so I'm closing this one as a dup and/or wrong repo.

**Comment by lamont-granquist** [comment]
Right so we can't implement .foodcritic in fieri because tools like stove strip that out of the upload.  I think that's still more evidence that the tools that upload need to be dumber and need to be enforcing less state about what is in the cookbook and just shipping a tarball.  The user should also be more able to determine what does and does not get uploaded.
