### ISSUE TITLE
Allow search of contributors

### ISSUE THREAD

**Issue by btm** [chef/supermarket#894]
Sometimes folks have problems getting their commit emails -> github -> supermarket all lined up and it's helpful to be able to search the list of CLAs/CCLAs. Currently we use the browser find option and go through each page of results, which is time consuming. It'd be great if the search drop down would include contributors (and/or user profiles?).

**Comment by cmluciano** [comment]
I' like to work on this. I see that there is a find_contributors action in the contributors controller but it is private(https://github.com/chef/supermarket/blob/master/app%2Fcontrollers%2Fcontributors_controller.rb#L51-52). Can this be made public so that I can leverage it?

cc @nellshamrell @smith

**Comment by smith** [comment]
@cmluciano I don't think that will really do anything. We probably want to behave the same way that searching for cookbooks does. See https://github.com/chef/supermarket/blob/54e70292e1d79e1bd6ff98ff3e192fb42feafff1/app/controllers/cookbooks_controller.rb#L5-L47

**Comment by cmluciano** [comment]
Thanks! Will def take a look
