### ISSUE TITLE
Can't find README after renaming cookbook folder.

### ISSUE THREAD

**Issue by tonytonyjan** [chef/supermarket#974]
`knife cookbook site share` take the directory name to generate archive file, while [supermarket looks at metadata](https://github.com/chef/supermarket/blob/master/app/models/cookbook_upload/parameters.rb#L188).

My cookbook's folder name is not equal to the name defined in `metadata.rb`, it cause me to spent hours to figure out what's going on. I have no idea this issue should belong to knife or supermarket, I hope they can be consistent.

**Comment by nellshamrell** [comment]
Will investigate whether some tool updates recently have fixed this issue, stay tuned!

**Comment by nellshamrell** [comment]
Hi again!

Sorry for the long delay on this.  I've just verified that knife cookbook site share will work and make the correct archive file, as well as upload correctly, when the metadata cookbook name is different from the folder name.  Looks like this has been fixed with knife, however if you run into this issue again please let us know and we will continue to troubleshoot!
