### ISSUE TITLE
pg_trgm extension is not loaded (cookbook) (ubuntu)

### ISSUE THREAD

**Issue by ccrebolder** [chef/supermarket#996]
At least when deploying from the cookbook, the pg_trgm postgres extension is not loaded, resulting in this error when using the "Add Collaborator" button:
```
E, [2015-03-04T10:45:58.811407 #19405] ERROR -- : PG::UndefinedFunction: ERROR:  function similarity(text, unknown) does not exist
```
I had to install the postgresql-contrib package on ubuntu and run `psql -d supermarket_production -c "create extension pg_trgm;"` to get it to work.

**Comment by leftathome** [comment]
:+1 , wasn't just you.  This happened deploying 1.5.0 for me via (custom-wrapped) omnibus-supermarket cookbook.

**Comment by smith** [comment]
This was fixed in the standalone cookbook in opscode-cookbooks/supermarket#85.

In Omnibus, we've updated to a version of omnibus-software that uses `make install-world` for postgres, which is effectively the same as including the contrib package. We [list the enabled extensions](https://github.com/chef/omnibus-supermarket/blob/5f8d8f00349b80c35f0199d31a741ae3a3557dd2/cookbooks/omnibus-supermarket/attributes/default.rb#L306) in the attributes and [enable them in the database recipe](https://github.com/chef/omnibus-supermarket/blob/5f8d8f00349b80c35f0199d31a741ae3a3557dd2/cookbooks/omnibus-supermarket/recipes/database.rb#L43-L49).
